In [1]:
l=[]
import mysql.connector as mycon
import random as r
from datetime import date
mydb=mycon.connect(host="localhost",user="root",password="1234",database="hotal_data")
my_cursor=mydb.cursor()
mydb.commit()
my_cursor.execute("select * from hotel")
result=my_cursor.fetchall()
for i in result:
    print(list(i))
    l.append(list(i))

[1597, datetime.date(2022, 5, 12), 'yash', 'Premium', 2, datetime.date(2022, 5, 14), 37, 16, 2, 17908]
[1897, datetime.date(2022, 2, 21), 'yogita', 'Deluxe', 3, datetime.date(2022, 2, 24), 26, 29, 1, 13958]
[2395, datetime.date(2023, 3, 3), 'nikita', 'Deluxe', 2, datetime.date(2023, 3, 7), 19, 20, 1, 11000]
[2597, datetime.date(2022, 3, 11), 'nidhi', 'Premium', 2, datetime.date(2022, 3, 14), 28, 12, 2, 20800]
[4564, datetime.date(2022, 7, 19), 'karan', 'classic', 2, datetime.date(2022, 7, 23), 32, 42, 1, 9000]
[4879, datetime.date(2022, 11, 11), 'ridhi', 'Deluxe', 2, datetime.date(2022, 11, 16), 41, 41, 2, 26400]
[7951, datetime.date(2022, 7, 12), 'bhavok', 'Deluxe', 1, datetime.date(2022, 7, 14), 24, 58, 2, 17289]
[8974, datetime.date(2022, 5, 10), 'sarthak', 'Premium', 2, datetime.date(2022, 5, 12), 31, 43, 1, 7800]

In [2]:
print("-------------------------------------------------Hotel Management System-----------------------------------------------------")
print("\n"*2)
def Table_str():
    """This function is use for the print the table in the structure format"""
    print()
    print("TABLE".center(121, "_"))
    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
    l1=[]
    for i in range(len(heading)):
        l1.append(len(heading[i]))
    for i in range(len(heading)):
        if i==0:
            print("|",end="")
        print(str(heading[i]).center(3),end="|")

    print("\n","-"*120)

    for i in range(len(l)):
        print(end="|")
        for j in range(len(l[i])):
            if "-" in str(l[i][j]):
                print(str(l[i][j]).center(l1[j]),end="|")
                continue
            print(str(l[i][j]).center(l1[j]).upper(),end="|")
        print()
    print( "-" * 121)
    print("\n")
Table_str()

-------------------------------------------------Hotel Management System-----------------------------------------------------




__________________________________________________________TABLE__________________________________________________________
| Adhaar No | Checkin Date |   Name  | Room Type | No of People | Checkout Date | Age | Room No | No of Rooms | Charges |
 ------------------------------------------------------------------------------------------------------------------------
|    1597   |  2022-05-12  |   YASH  |  PREMIUM  |      2       |   2022-05-14  |  37 |    16   |      2      |  17908  |
|    1897   |  2022-02-21  |  YOGITA |   DELUXE  |      3       |   2022-02-24  |  26 |    29   |      1      |  13958  |
|    2395   |  2023-03-03  |  NIKITA |   DELUXE  |      2       |   2023-03-07  |  19 |    20   |      1      |  11000  |
|    2597   |  2022-03-11  |  NIDHI  |  PREMIUM  |      2       |   2022-03-14  |  28 |    12   |      2      |  20800  |
|    4564   |  2022-07-19  |  KARAN  |  CLASSIC  |      2       |   2022-07-23  |  32 |    42   |      1      |   9000  |
|    4879   |  2022-11-11  |  RIDHI  |   DELUXE  |      2       |   2022-11-16  |  41 |    41   |      2      |  26400  |
|    7951   |  2022-07-12  |  BHAVOK |   DELUXE  |      1       |   2022-07-14  |  24 |    58   |      2      |  17289  |
|    8974   |  2022-05-10  | SARTHAK |  PREMIUM  |      2       |   2022-05-12  |  31 |    43   |      1      |   7800  |
-------------------------------------------------------------------------------------------------------------------------

In [3]:
'''my_cursor.execute("update hotel set charges=10400 where name='yash';")
mydb.commit()'''

'my_cursor.execute("update hotel set charges=10400 where name=\'yash\';")\nmydb.commit()'

In [4]:
def r_no():
    """This function is used for the No of rooms Available in the hotel With the random room no you get alloted"""
    r_no=[]
    for i in range(len(l)):
        r_no.append(l[i][7])
    ro=[]
    for i in range(1,58):
        if i not in r_no:
            ro.append(i)
    print()
    print(" "*30,"The Total no of the Rooms available in the Hotel are : ",len(ro))
    print()

    while True:
        x=r.randint(1,58)
        if x not in r_no:
            return x
            break
        else:
            continue

In [5]:
def date_Format(a):
    if "-" in a:
        s=a.split("-")
        s.reverse()
        s="-".join(s)
        return s
    elif "/" in a:
        s=a.split("/")
        s.reverse()
        s="-".join(s)
        return s

In [6]:
def check_date(check_in,check_out):
    if "-" in check_in:
        c1=check_in.split("-")
        c2=check_out.split("-")
        a=0
        if c1[0]<=c2[0]:
            if c1[1]<=c2[1]:
                if c1[2]<=c2[2]:
                    z=True
                    return z
        if a==0:
            z=False
            return z
    elif "/" in check_in:
        c1=check_in.split("/")
        c2=check_out.split("/")
        a=0
        if c1[0]<=c2[0]:
            if c1[1]<=c2[1]:
                if c1[2]<=c2[2]:
                    z=True
                    return z
        if a==0:
            z=False
            return z

In [7]:
def check_date1(c1,c2):
    if c1 <= c2:
        x=True
        return x
    else:
        x=False
        return x

In [8]:
def date_ch_after_form1(ch_in,i,j):
    ch_in=date.fromisoformat(ch_in)
    if ch_in<=l[i][j]:
        x=True
        return x
    else:
        x=False
        return x

In [9]:
def date_ch_after_form2(ch_out,i,j):
    ch_out=date.fromisoformat(ch_out)
    if ch_out>=l[i][j]:
        x=True
        return x
    else:
        x=False
        return x

In [10]:
def no_of_days(c_in,c_out):
    date1=date.fromisoformat(c_in)
    date2=date.fromisoformat(c_out)
    gap=str(date1-date2)
    for i in range(len(gap)):
        if gap[i].isdigit():
            g=int(gap[i])
            break
    g+=1
    return g

In [11]:
def no_of_days1(c_in,c_out):
    gap=str(c_in-c_out)
    for i in range(len(gap)):
        if gap[i].isdigit():
            g=int(gap[i])
            break
    g+=1
    return g

In [12]:
def add_data(adh,check_in,name,room_type,no_of_persons,check_out,age,room_no,no_of_rooms,days):
    cha=0
    if room_type.lower()=="classic":
        cha=days*1800*no_of_rooms
    elif room_type.lower()=="deluxe":
        cha=days*2200*no_of_rooms
    elif room_type.lower()=="premium":
        cha=days*2600*no_of_rooms
    my_cursor.execute("insert into hotel values(%d,'%s','%s','%s',%d,'%s',%d,%d,%d,%d);"%(adh,check_in,name,room_type,no_of_persons,check_out,age,room_no,no_of_rooms,cha))
    mydb.commit()
    print()
    print(" "*50,"Value has been entered")
    Table_str()

In [ ]:
while True:
    print()
    print("-------------------------------------------------Hotel Management System-----------------------------------------------------")
    print("\n")
    print(" "*20,"_"*81)
    print(" "*20,"|","MENU".center(77,"_"),"|")
    print(" "*20,"|"," "*77,"|")
    print(" "*20,"|      ","1.ADD RECORDS".center(20), " ".center(24) , "2.MODIFY YOUR RECORD".center(15)," "*4,"|")
    print(" "*20,"|"," ".center(77),"|")
    print(" "*20,"|     ","3.SEARCH FOR THE RECORD".center(13), " ".center(20) , "4.DELETE THE RECORD".center(23)," "*3,"|")
    print(" "*20,"|"," ".center(77),"|")
    print(" "*20,"|      ","5.TOTAL AMOUNT".center(20)," ".center(21) , "6.AVALIBILITY OF THE ROOM".center(16)," "*2,"|")
    print(" "*20,"|"," "*77,"|")
    print(" "*20,"|","7.ROOM SERVICE OPTIONS".center(32)," ".center(20),"8.SHOW ALL DATA"," "*7,"|")
    print(" "*20,"|"," "*77,"|")
    print(" "*20,"|","9.EXIT".center(77,"_"),"|")
    print()
    ch=int(input("Now you can enter your choice as per your requirement's in the data : "))
    if ch==1:
        print()
        print("Now you can ADD the records of the Database".center(122))
        print()
        adh=int(input("Enter the adhaar card number of the person :"))
        check_in=input("Enter the date of the CheckIn of the person(dd-mm-yyyy) :")
        name=input("Enter the name of the person :")
        print()
        print(" "*45," ____________________")
        print(" "*45,"|_____Room Types_____|")
        print(" "*45,"| 1.Classic    -1800 |")
        print(" "*45,"| 2.Deluxe     -2200 |")
        print(" "*45,"| 3.Premium    -2600 |")
        print(" "*45,"----------------------")
        print()
        c=int(input("Enter Your choice of Room Type :"))
        if c==1:
            room_type="Classic"
        elif c==2:
            room_type="Deluxe"
        elif c==3:
            room_type="Premium"
        else:
            print("You have enter the wrong choice")
            room_type="Classic"                                       # room_type is by defalut is to be classic 
        no_of_persons=int(input("Enter the Total no of Members with them :"))
        check_out=input("Enter the date of the CheckOut of the person(dd-mm-yyyy) :")
        ab=check_date(check_in,check_out)
        if ab==False:
            print()
            print(" "*40,"The Date you have Enter is not Correct")
            break
        elif ab==True:
            print()
            print(" "*50,"The Date is Valid")
            print()
        check_in=date_Format(check_in)
        check_out=date_Format(check_out)
        days=no_of_days(check_in,check_out)
        age=int(input("Enter the Age of the person :"))
        if age>=18:
            pass
        elif age<18:
            print("You are not eligible for the booking")
            break
        room_no=r_no()
        no_of_rooms=int(input("Enter the no of rooms booked by the user :"))
        add_data(adh,check_in,name,room_type,no_of_persons,check_out,age,room_no,no_of_rooms,days)
    elif ch==2:
        print()
        print("Now you can Modify the record in the Database".center(122))
        print()
        print("Now here in the Database".center(121))
        Table_str()
        print(" "*37,"Now what do you want to Change in this Database")
        print(" "*40,"__________________________________")
        print(" "*40,"|___________MODIFY MENU__________|")
        print(" "*40,"|                                |")
        print(" "*40,"|    1.NAME         2.CHECK IN   |")
        print(" "*40,"|                                |")
        print(" "*40,"|  3.CHECK OUT      4.ROOM TYPE  |")
        print(" "*40,"|                                |")
        print(" "*40,"| 5.NO OF PEOPLE      6.AGE      |")
        print(" "*40,"|                                |")
        print(" "*40,"|   7.ROOM NO      8.NO OF ROOMS |")
        print(" "*40,"|                                |")
        print(" "*40,"|_____________9.EXIT_____________|")
        print()
        c=int(input("Enter your choice of the modify :"))
        if c==1:
            print()
            print("You can Modify the Name of the Person in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print("\n")
                    n=input("Enter the New Name for the Database :")
                    my_cursor.execute("update hotel set name='%s' where adhaar_card_no=%d;"%(n,ad))
                    mydb.commit()
                    print("The Name of the Person has been Modified in the Database".center(120))
            if a==0:
                print("The Data is not Found in the Database".center(120))
                
        elif c==2:
            print()
            print("You can Modify the CheckIn Date of the Person in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print("\n")
                    n=input("Enter the date of the CheckIn Date of the person(dd-mm-yyyy) :")
                    n=date_Format(n)
                    ab=date_ch_after_form1(n,i,5)
                    if ab==False:
                        print()
                        print(" "*40,"The Date you have Enter is not Correct")
                        break
                    elif ab==True:
                        print()
                        print(" "*50,"The Date is Valid")
                        print()
                    
                    my_cursor.execute("update hotel set checkin_date='%s' where adhaar_card_no=%d;"%(n,ad))
                    mydb.commit()
                    gap=no_of_days1(l[i][1],l[i][5])
                    if l[i][3].lower()=="classic":
                        price=1800*gap*l[i][8]
                    elif l[i][3].lower()=='deluxe':
                        price=2200*gap*l[i][8]
                    elif l[i][3].lower()=="premium":
                        price=2600*gap*l[i][8]
                    my_cursor.execute("update hotel set charges=%d where adhaar_card_no=%d;"%(price,ad))
                    mydb.commit()
                    print("The CheckIn Date of the Person has been Modified in the Database".center(120))
            
            if a==0:
                print("The Data is not Found in the Database".center(120))
        
        elif c==3:
            print()
            print("You can Modify the CheckOut Date of the Person in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print("\n")
                    n=input("Enter the date of the CheckOut Date of the person(dd-mm-yyyy) :")
                    n=date_Format(n)
                    ab=date_ch_after_form2(n,i,1)
                    if ab==False:
                        print()
                        print(" "*40,"The Date you have Enter is not Correct")
                        break
                    elif ab==True:
                        print()
                        print(" "*50,"The Date is Valid")
                        print()
                    my_cursor.execute("update hotel set checkout_date='%s' where adhaar_card_no=%d;"%(n,ad))
                    mydb.commit()
                    gap=no_of_days1(l[i][1],l[i][5])
                    if l[i][3].lower()=="classic":
                        price=1800*gap*l[i][8]
                    elif l[i][3].lower()=='deluxe':
                        price=2200*gap*l[i][8]
                    elif l[i][3].lower()=="premium":
                        price=2600*gap*l[i][8]
                    my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
                    mydb.commit()
                    print("The CheckOut Date of the Person has been Modified in the Database".center(120))
            
            if a==0:
                print("The Data is not Found in the Database".center(120))
                    
        elif c==4:
            print()
            print("You can Modify the Room Type of the Person in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
                    print("Now you can Modify the Room Type of the Person".center(120))
                    print()
                    print(" "*45," ____________________")
                    print(" "*45,"|_____Room Types_____|")
                    print(" "*45,"| 1.Classic    -1800 |")
                    print(" "*45,"| 2.Deluxe     -2200 |")
                    print(" "*45,"| 3.Premium    -2600 |")
                    print(" "*45,"----------------------")
                    print()
                    gap=no_of_days1(l[i][1],l[i][5])
                    c1=int(input("Enter Your choice of Room Type :"))
                    if c1==1:
                        room_type="Classic"
                        price=1800*gap*l[i][8]
                    elif c1==2:
                        room_type="Deluxe"
                        price=2200*gap*l[i][8]
                    elif c1==3:
                        room_type="Premium"
                        price=2600*gap*l[i][8]
                    else:
                        print("You have enter the wrong choice")
                        room_type="Classic"
                        price=1800*gap*l[i][8]
                    my_cursor.execute("update hotel set room_type= '%s' where adhaar_card_no=%d;"%(room_type,ad))
                    mydb.commit()
                    my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
                    mydb.commit()
                    print("The Room Type of the Person have been Modified in the Database".center(120))
                    
            if a==0:
                print("The Data is not found in the Database".center(120))
        
        elif c==5:
            print()
            print("You can Modify the No of Persons add in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now enter the Updated no of People in the Database".center(120))
            print()
            no_people=int(input("Enter the no of People with Customer :"))
            my_cursor.execute("update hotel set no_person_stay=%d where adhaar_card_no=%d;"%(no_people,ad))
            mydb.commit()
            print()
            print("The No of People Data has been Updated in the Database".center(120))
        
        elif c==6:
            print()
            print("You can Modify the Age in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now Enter the Updated Age of the Person in the Database".center(120))
            print()
            age=int(input("Enter the New Age of the Person in the Database :"))
            if age>=18:
                print("The Age of the person is Valid".center(120))
            elif age<18:
                print("The Age of the Person is not Valid")
                break
            my_cursor.execute("update hotel set age=%d where adhaar_card_no=%d;"%(age,ad))
            mydb.commit()
            print()
            print("The Age of the Person has been Modified in the Database".center(120))
            
        elif c==7:
            print()
            print("You can Modify the Room No in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            r_no=[]
            for i in range(len(l)):
                r_no.append(l[i][7])
            ro=[]
            for i in range(1,58):
                if i not in r_no:
                    ro.append(i)
            print()
            print(" "*30,"The Total no of the Rooms available in the Hotel are : ",len(ro))
            print()

            while True:
                r=int(input("Enter the Room No you want :"))
                if r not in r_no:
                    print(f"Room No {r} is Alloted to you".center(120))
                    break
                else:
                    print("The Room is already Occupied".center(120))
                    print()
                    print("Try Again".center(120))
                    print()
            my_cursor.execute("update hotel set room_no=%d where adhaar_card_no=%d;"%(r,ad))
            mydb.commit()
            print()
            print("The Room No of the Person has been Modified in the Database".center(120))
        
        elif c==8:
            print()
            print("You can Modify the No of Rooms in the Database".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for i in range(len(l)):
                        if l[i][0]==ad:
                            print(end="|")
                            for j in range(len(l[i])):
                                if "-" in str(l[i][j]):
                                    print(str(l[i][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[i][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now you can Modify the No of Rooms the user want to Book")
            print()
            r=int(input("Enter the No of Rooms Person want to Book :"))
            gap=no_of_days1(l[i][1],l[i][5])
            if l[i][3].lower()=="classic":
                price=1800*gap*r
            elif l[i][3].lower()=='deluxe':
                price=2200*gap*r
            elif l[i][3].lower()=="premium":
                price=2600*gap*r
            my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
            mydb.commit()
            my_cursor.execute("update hotel set no_of_rooms_booked= %d where adhaar_card_no=%d;"%(r,ad))
            mydb.commit()
            print()
            print("The No of Rooms Booked of the Person has been Modified in the Database".center(120))
        
        elif c==9:
            print("Now You have been Exited from the Modifying Menu".center(120))
        else:
            print("You have enter the Wrong choice".center(120))
            
    elif ch==3:
        Table_str()
        print()
        print("You can Search the Database Through the Adhaar Card No".center(120))
        print()
        ad=int(input("Enter the Adhaar no of the Person :"))
        a=0
        for i in range(len(l)):
            if l[i][0]==ad:
                print()
                a=1
                print("The Value is found in the database".center(120))
                print()
                print("TABLE".center(121, "_"))
                heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                l1=[]
                for i in range(len(heading)):
                    l1.append(len(heading[i]))
                for i in range(len(heading)):
                    if i==0:
                        print("|",end="")
                    print(str(heading[i]).center(3),end="|")
                print("\n","-"*120)
                for i in range(len(l)):
                    if l[i][0]==ad:
                        print(end="|")
                        for j in range(len(l[i])):
                            if "-" in str(l[i][j]):
                                print(str(l[i][j]).center(l1[j]),end="|")
                                continue
                            print(str(l[i][j]).center(l1[j]).upper(),end="|")
                        print()
                        break
                print( "-" * 121)
                print()
    
    elif ch==4:
        Table_str()
        print()
        print("You can Search the Database Through the Adhaar Card No".center(120))
        print()
        ad=int(input("Enter the Adhaar no of the Person :"))
        a=0
        for i in range(len(l)):
            if l[i][0]==ad:
                print()
                a=1
                print("The Value is found in the database".center(120))
                print()
                print("TABLE".center(121, "_"))
                heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                l1=[]
                for i in range(len(heading)):
                    l1.append(len(heading[i]))
                for i in range(len(heading)):
                    if i==0:
                        print("|",end="")
                    print(str(heading[i]).center(3),end="|")
                print("\n","-"*120)
                for i in range(len(l)):
                    if l[i][0]==ad:
                        print(end="|")
                        for j in range(len(l[i])):
                            if "-" in str(l[i][j]):
                                print(str(l[i][j]).center(l1[j]),end="|")
                                continue
                            print(str(l[i][j]).center(l1[j]).upper(),end="|")
                        print()
                        break
                print( "-" * 121)
                print()
        y_n=input("Are you sure to Delete this Person Data(Yes/No) :")
        if y_n in ["Yes","yes","y","Y"]:
            my_cursor.execute("delete from hotel where adhaar_card_no=%d;"%(ad))
            mydb.commit()
            print()
            print("Now the Data of the Person has been Deleted from the Database".center(120))
            print()
        elif y_n in ["No","no","N","n"]:
            print()
            print("Now you have been Exited From the Delete Function".center(120))
            print()
        else:
            print("You have Enter the Wrong Choice")
            
    elif ch==5:
        Table_str()
        print()
        print("You can Search the Database Through the Adhaar Card No".center(120))
        print()
        ad=int(input("Enter the Adhaar no of the Person :"))
        a=0
        for i in range(len(l)):
            if l[i][0]==ad:
                print()
                a=1
                print("The Value is found in the database".center(120))
                print()
                print("TABLE".center(121, "_"))
                heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                l1=[]
                for i in range(len(heading)):
                    l1.append(len(heading[i]))
                for i in range(len(heading)):
                    if i==0:
                        print("|",end="")
                    print(str(heading[i]).center(3),end="|")
                print("\n","-"*120)
                for k in range(len(l)):
                    if l[k][0]==ad:
                        print(end="|")
                        for j in range(len(l[k])):
                            if "-" in str(l[k][j]):
                                print(str(l[k][j]).center(l1[j]),end="|")
                                continue
                            print(str(l[k][j]).center(l1[j]).upper(),end="|")
                        print()
                        break
                print( "-" * 121)
                print()
        dis=int(l[k][9]*18/100)
        price=int(l[k][9]+l[k][9]*18/100)
        if price>=14000:
            d=500
            price-=500
        else:
            d=0
            pass
        print()
        print("_"*120)
        print(f"               Total Bill of {l[k][2].upper()}            ".center(120))
        print("                                                    ".center(120))
        print(f" The Total No of Amount You have to gave is - {l[k][9]}".center(120))
        print("                                                    ".center(120))
        print(f" Total Tax of the Room is                   - {dis}".center(120))
        print("                                                    ".center(120))
        print(f" Total Discount                              - {d}".center(120))
        print("                                                    ".center(120))
        print(f"   Total Amount                               - {price}".center(120))
        print("                                                    ".center(120))
        print("_"*120)
        print()
        my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
        mydb.commit()
        print("Now the Price has been changed after the Tax and Discount".center(120))
    
    elif ch==6:
        Table_str()
        print()
        r_no=[]
        for i in range(len(l)):
            r_no.append(l[i][7])
        ro=[]
        for i in range(1,58):
            if i not in r_no:
                ro.append(i)
        print()
        print(" "*30,"The Total no of the Rooms available in the Hotel are : ",len(ro))
        print()
        print("Now you can Search for Room No to Check it is Available or Not".center(120))
        print()
        n=int(input("Enter the Room No you want to Check (1-58):"))
        z=[]
        if n not in ro:
            print()
            print("The Room you Searched is Occupied".center(120))
        elif n in ro:
            print()
            print("The Room you Searched is Available".center(120))
            
    elif ch==7:
        print()
        print("Now You can Select the Room Service you want for You".center(125))
        print()
        print(" "*40,"__________________________________________")
        print(" "*40,"|__________________Menu__________________|")
        print(" "*40,"|                                        |")
        print(" "*40,"|   1.Food orders       2.Gym Service    |")
        print(" "*40,"|                                        |")
        print(" "*40,"|  3.Room Service   4.Broken Prop Charge |")
        print(" "*40,"|                                        |")
        print(" "*40,"|_________________5.Exit_________________|")
        print()
        c=int(input("Enter your Choice :"))
        
        if c==1:
            Table_str()
            print("You can Search the Database Through the Adhaar Card No".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for k in range(len(l)):
                        if l[k][0]==ad:
                            print(end="|")
                            for j in range(len(l[k])):
                                if "-" in str(l[k][j]):
                                    print(str(l[k][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[k][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now Enter the Total Orders Done by the Person".center(120))
            print()
            t_food_ord=int(input("Enter the Total Amount of food Ordered from the Person :"))
            print()
            price = l[k][9] + t_food_ord
            my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
            mydb.commit()
            print("The Food Charges has been added in the Database".center(120))
        
        elif c==2:
            Table_str()
            print()
            print("You can Search the Database Through the Adhaar Card No".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for k in range(len(l)):
                        if l[k][0]==ad:
                            print(end="|")
                            for j in range(len(l[k])):
                                if "-" in str(l[k][j]):
                                    print(str(l[k][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[k][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now Enter the Gym Service Charges used by the Person".center(120))
            print()
            t_food_ord=int(input("Enter the Total Amount of Gym Charges used from the Person :"))
            print()
            price = l[k][9] + t_food_ord
            my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
            mydb.commit()
            print("The Gym Charges has been added in the Database".center(120))
        
        elif c==3:
            Table_str()
            print()
            print("You can Search the Database Through the Adhaar Card No".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for k in range(len(l)):
                        if l[k][0]==ad:
                            print(end="|")
                            for j in range(len(l[k])):
                                if "-" in str(l[k][j]):
                                    print(str(l[k][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[k][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now Enter the Room Service Charges used by the Person".center(120))
            print()
            t_food_ord=int(input("Enter the Room Service Charges from the Person :"))
            print()
            price = l[k][9] + t_food_ord
            my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
            mydb.commit()
            print("The Room Service Charges has been added in the Database".center(120))
            
        elif c==4:
            Table_str()
            print()
            print("You can Search the Database Through the Adhaar Card No".center(120))
            print()
            ad=int(input("Enter the Adhaar no of the Person :"))
            a=0
            for i in range(len(l)):
                if l[i][0]==ad:
                    print()
                    a=1
                    print("The Value is found in the database".center(120))
                    print()
                    print("TABLE".center(121, "_"))
                    heading=[" Adhaar No "," Checkin Date ","   Name  "," Room Type "," No of People "," Checkout Date "," Age "," Room No "," No of Rooms "," Charges "]
                    l1=[]
                    for i in range(len(heading)):
                        l1.append(len(heading[i]))
                    for i in range(len(heading)):
                        if i==0:
                            print("|",end="")
                        print(str(heading[i]).center(3),end="|")
                    print("\n","-"*120)
                    for k in range(len(l)):
                        if l[k][0]==ad:
                            print(end="|")
                            for j in range(len(l[k])):
                                if "-" in str(l[k][j]):
                                    print(str(l[k][j]).center(l1[j]),end="|")
                                    continue
                                print(str(l[k][j]).center(l1[j]).upper(),end="|")
                            print()
                            break
                    print( "-" * 121)
                    print()
            print("Now Enter the Property Damage Done by the Person".center(120))
            print()
            t_food_ord=int(input("Enter the Property Damage Charges Done from the Person :"))
            print()
            price = l[k][9] + t_food_ord
            my_cursor.execute("update hotel set charges= %d where adhaar_card_no=%d;"%(price,ad))
            mydb.commit()
            print("The Property Damage Charges has been added in the Database".center(120))
            
        elif c==5:
            print()
            print("Now you have been Exited from the Service Charges Menu".center(120))
            print()
        
        else:
            print()
            print("You have Enter Wrong Choice".center(120))
            print()
    
    elif ch==8:
        Table_str()
        
    elif ch==9:
        print()
        print("Now you have been Exited from the Main Menu".center(120))
        print()
        break
    else:
        print()
        print("Now you have Enter the Wrong Choice".center(120))
        print()
 
print("""🙏""".center(115))

-------------------------------------------------Hotel Management System-----------------------------------------------------


                     _________________________________________________________________________________
                     | _____________________________________MENU____________________________________ |
                     |                                                                               |
                     |          1.ADD RECORDS                              2.MODIFY YOUR RECORD      |
                     |                                                                               |
                     |      3.SEARCH FOR THE RECORD                        4.DELETE THE RECORD       |
                     |                                                                               |
                     |          5.TOTAL AMOUNT                          6.AVALIBILITY OF THE ROOM    |
                     |                                                                               |
                     |      7.ROOM SERVICE OPTIONS                           8.SHOW ALL DATA         |
                     |                                                                               |
                     | ____________________________________9.EXIT___________________________________ |

Now you can enter your choice as per your requirement's in the data : 5

__________________________________________________________TABLE__________________________________________________________
| Adhaar No | Checkin Date |   Name  | Room Type | No of People | Checkout Date | Age | Room No | No of Rooms | Charges |
 ------------------------------------------------------------------------------------------------------------------------
|    1597   |  2022-05-12  |   YASH  |  PREMIUM  |      2       |   2022-05-14  |  37 |    16   |      2      |  17908  |
|    1897   |  2022-02-21  |  YOGITA |   DELUXE  |      3       |   2022-02-24  |  26 |    29   |      1      |  13958  |
|    2395   |  2023-03-03  |  NIKITA |   DELUXE  |      2       |   2023-03-07  |  19 |    20   |      1      |  11000  |
|    2597   |  2022-03-11  |  NIDHI  |  PREMIUM  |      2       |   2022-03-14  |  28 |    12   |      2      |  20800  |
|    4564   |  2022-07-19  |  KARAN  |  CLASSIC  |      2       |   2022-07-23  |  32 |    42   |      1      |   9000  |
|    4879   |  2022-11-11  |  RIDHI  |   DELUXE  |      2       |   2022-11-16  |  41 |    41   |      2      |  26400  |
|    7951   |  2022-07-12  |  BHAVOK |   DELUXE  |      1       |   2022-07-14  |  24 |    58   |      2      |  17289  |
|    8974   |  2022-05-10  | SARTHAK |  PREMIUM  |      2       |   2022-05-12  |  31 |    43   |      1      |   7800  |
-------------------------------------------------------------------------------------------------------------------------



                                 You can Search the Database Through the Adhaar Card No

Enter the Adhaar no of the Person :1597

                                           The Value is found in the database

__________________________________________________________TABLE__________________________________________________________
| Adhaar No | Checkin Date |   Name  | Room Type | No of People | Checkout Date | Age | Room No | No of Rooms | Charges |
 ------------------------------------------------------------------------------------------------------------------------
|    1597   |  2022-05-12  |   YASH  |  PREMIUM  |      2       |   2022-05-14  |  37 |    16   |      2      |  17908  |
-------------------------------------------------------------------------------------------------------------------------


________________________________________________________________________________________________________________________
                                                    Total Bill of YASH

                                   The Total No of Amount You have to gave is - 17908

                                    Total Tax of the Room is                   - 3223

                                    Total Discount                              - 500

                                    Total Amount                               - 20631

________________________________________________________________________________________________________________________

                               Now the Price has been changed after the Tax and Discount

-------------------------------------------------Hotel Management System-----------------------------------------------------


                     _________________________________________________________________________________
                     | _____________________________________MENU____________________________________ |
                     |                                                                               |
                     |          1.ADD RECORDS                              2.MODIFY YOUR RECORD      |
                     |                                                                               |
                     |      3.SEARCH FOR THE RECORD                        4.DELETE THE RECORD       |
                     |                                                                               |
                     |          5.TOTAL AMOUNT                          6.AVALIBILITY OF THE ROOM    |
                     |                                                                               |
                     |      7.ROOM SERVICE OPTIONS                           8.SHOW ALL DATA         |
                     |                                                                               |
                     | ____________________________________9.EXIT___________________________________ |